"""
Armor Prototypes

MajorMUD-style armor prototypes for all tiers (cloth → leather → medium → heavy).
Use with evennia.create_object() or the @spawn command.

Each prototype uses typeclass typeclasses.armor.Armor and sets slot, ac_bonus,
dr_bonus, armor_type, weight, and value.
"""

CLOTH_ARMOR = [
    {
        "prototype_key": "PLAIN_ROBES",
        "typeclass": "typeclasses.armor.Armor",
        "key": "plain robes",
        "desc": "Simple undyed robes of rough-spun cloth.",
        "db.slot": "chest",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "cloth",
        "db.weight": 1.0,
        "db.value": 5,
    },
    {
        "prototype_key": "CLOTH_CAP",
        "typeclass": "typeclasses.armor.Armor",
        "key": "cloth cap",
        "desc": "A simple cloth cap offering minimal protection.",
        "db.slot": "head",
        "db.ac_bonus": 0,
        "db.dr_bonus": 0,
        "db.armor_type": "cloth",
        "db.weight": 0.2,
        "db.value": 2,
    },
]

LEATHER_ARMOR = [
    {
        "prototype_key": "LEATHER_CAP",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather cap",
        "desc": "A tanned leather cap with a short brim.",
        "db.slot": "head",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 0.5,
        "db.value": 10,
    },
    {
        "prototype_key": "LEATHER_JERKIN",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather jerkin",
        "desc": "A fitted jerkin of hardened leather covering the torso.",
        "db.slot": "chest",
        "db.ac_bonus": 2,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 3.0,
        "db.value": 25,
    },
    {
        "prototype_key": "LEATHER_BRACERS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather bracers",
        "desc": "Stiff leather bracers strapped to the forearms.",
        "db.slot": "arms",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 0.5,
        "db.value": 8,
    },
    {
        "prototype_key": "LEATHER_GLOVES",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather gloves",
        "desc": "Supple leather gloves that protect the hands.",
        "db.slot": "hands",
        "db.ac_bonus": 0,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 0.3,
        "db.value": 5,
    },
    {
        "prototype_key": "LEATHER_BELT",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather belt",
        "desc": "A wide leather belt with a plain iron buckle.",
        "db.slot": "waist",
        "db.ac_bonus": 0,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 0.5,
        "db.value": 5,
    },
    {
        "prototype_key": "LEATHER_LEGGINGS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather leggings",
        "desc": "Tanned leather leggings reinforced at the knees.",
        "db.slot": "legs",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 2.0,
        "db.value": 15,
    },
    {
        "prototype_key": "LEATHER_BOOTS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "leather boots",
        "desc": "Sturdy leather boots that come to the knee.",
        "db.slot": "feet",
        "db.ac_bonus": 0,
        "db.dr_bonus": 0,
        "db.armor_type": "leather",
        "db.weight": 1.0,
        "db.value": 8,
    },
]

MEDIUM_ARMOR = [
    {
        "prototype_key": "CHAIN_COIF",
        "typeclass": "typeclasses.armor.Armor",
        "key": "chain coif",
        "desc": "A close-fitting mail hood of interlocked iron rings.",
        "db.slot": "head",
        "db.ac_bonus": 2,
        "db.dr_bonus": 0,
        "db.armor_type": "medium",
        "db.weight": 2.0,
        "db.value": 30,
    },
    {
        "prototype_key": "CHAIN_MAIL",
        "typeclass": "typeclasses.armor.Armor",
        "key": "chain mail",
        "desc": "A hauberk of interlocked iron rings covering torso and upper thighs.",
        "db.slot": "chest",
        "db.ac_bonus": 4,
        "db.dr_bonus": 1,
        "db.armor_type": "medium",
        "db.weight": 15.0,
        "db.value": 80,
    },
    {
        "prototype_key": "CHAIN_VAMBRACES",
        "typeclass": "typeclasses.armor.Armor",
        "key": "chain vambraces",
        "desc": "Linked chain sleeves protecting the arms.",
        "db.slot": "arms",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "medium",
        "db.weight": 2.0,
        "db.value": 20,
    },
    {
        "prototype_key": "CHAIN_LEGGINGS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "chain leggings",
        "desc": "Mail leggings of interlocked rings from hip to knee.",
        "db.slot": "legs",
        "db.ac_bonus": 2,
        "db.dr_bonus": 1,
        "db.armor_type": "medium",
        "db.weight": 8.0,
        "db.value": 50,
    },
    {
        "prototype_key": "IRON_BOOTS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "iron boots",
        "desc": "Heavy boots reinforced with iron plates over the toes and shins.",
        "db.slot": "feet",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "medium",
        "db.weight": 3.0,
        "db.value": 25,
    },
]

HEAVY_ARMOR = [
    {
        "prototype_key": "IRON_HELM",
        "typeclass": "typeclasses.armor.Armor",
        "key": "iron helm",
        "desc": "A full iron helm with a fixed nasal bar and cheek guards.",
        "db.slot": "head",
        "db.ac_bonus": 3,
        "db.dr_bonus": 1,
        "db.armor_type": "heavy",
        "db.weight": 5.0,
        "db.value": 60,
    },
    {
        "prototype_key": "PLATE_MAIL",
        "typeclass": "typeclasses.armor.Armor",
        "key": "plate mail",
        "desc": "Full plate armor of overlapping steel panels, the pinnacle of martial protection.",
        "db.slot": "chest",
        "db.ac_bonus": 6,
        "db.dr_bonus": 3,
        "db.armor_type": "heavy",
        "db.weight": 25.0,
        "db.value": 200,
    },
    {
        "prototype_key": "IRON_VAMBRACES",
        "typeclass": "typeclasses.armor.Armor",
        "key": "iron vambraces",
        "desc": "Solid iron plates strapped over the forearms.",
        "db.slot": "arms",
        "db.ac_bonus": 2,
        "db.dr_bonus": 0,
        "db.armor_type": "heavy",
        "db.weight": 4.0,
        "db.value": 40,
    },
    {
        "prototype_key": "IRON_GAUNTLETS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "iron gauntlets",
        "desc": "Articulated iron gauntlets covering the hands and fingers.",
        "db.slot": "hands",
        "db.ac_bonus": 1,
        "db.dr_bonus": 1,
        "db.armor_type": "heavy",
        "db.weight": 2.0,
        "db.value": 30,
    },
    {
        "prototype_key": "PLATE_LEGGINGS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "plate leggings",
        "desc": "Articulated steel plates protecting the legs from hip to ankle.",
        "db.slot": "legs",
        "db.ac_bonus": 4,
        "db.dr_bonus": 1,
        "db.armor_type": "heavy",
        "db.weight": 12.0,
        "db.value": 100,
    },
    {
        "prototype_key": "IRON_SABATONS",
        "typeclass": "typeclasses.armor.Armor",
        "key": "iron sabatons",
        "desc": "Articulated iron foot armor covering the entire foot.",
        "db.slot": "feet",
        "db.ac_bonus": 2,
        "db.dr_bonus": 0,
        "db.armor_type": "heavy",
        "db.weight": 4.0,
        "db.value": 35,
    },
]

## ── New Silvermere Armor ─────────────────────────────────────────────────────

NEW_SILVERMERE_ARMOR = [
    {
        "prototype_key": "SCALE_MAIL",
        "typeclass": "typeclasses.armor.Armor",
        "key": "scale mail",
        "desc": "Overlapping iron scales riveted to a leather backing. Heavier than chain but offers stronger protection.",
        "db.slot": "chest",
        "db.ac_bonus": 5,
        "db.dr_bonus": 2,
        "db.armor_type": "medium",
        "db.weight": 18.0,
        "db.value": 150,
    },
    {
        "prototype_key": "TOWER_SHIELD",
        "typeclass": "typeclasses.armor.Armor",
        "key": "tower shield",
        "desc": "A full-body shield of iron-banded oak, tall enough to shelter behind completely. Extremely heavy.",
        "db.slot": "off_hand",
        "db.ac_bonus": 3,
        "db.dr_bonus": 0,
        "db.armor_type": "heavy",
        "db.item_type": "shield",
        "db.weight": 12.0,
        "db.value": 120,
    },
    {
        "prototype_key": "GREATCLOAK",
        "typeclass": "typeclasses.armor.Armor",
        "key": "greatcloak",
        "desc": "A heavy wool cloak with an oilskin outer layer, lined with rabbit fur. It turns cold and rain alike.",
        "db.slot": "waist",
        "db.ac_bonus": 1,
        "db.dr_bonus": 0,
        "db.armor_type": "cloth",
        "db.weight": 2.0,
        "db.value": 30,
    },
]

# All prototypes combined
ALL_ARMOR_PROTOTYPES = CLOTH_ARMOR + LEATHER_ARMOR + MEDIUM_ARMOR + HEAVY_ARMOR + NEW_SILVERMERE_ARMOR
